grafana: fix { => unified_}alerting #1269
Role error was:
    TASK [bluebanquise.infrastructure.grafana : service <|> Wait for grafana to start (http/s)]
    […]
    [ERROR]: Task failed: Module failed: Timeout when waiting for 0.0.0.0:3000
    Origin: /home/bb/.ansible/collections/ansible_collections/bluebanquise/infrastructure/roles/grafana/tasks/main.yml:80:3

    78   ansible.builtin.meta: flush_handlers
    79
    80 - name: service <|> Wait for grafana to start (http/s)
         ^ column 3

    fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for 0.0.0.0:3000"}

Grafana v13.1.1 error was:
    logger=settings t=2026-08-10T18:37:26.197688584+02:00 level=info msg="Starting Grafana" version=13.1.1 commit=a9cee6e1724a455676bb6c05eef7fc54aa4b19f4 branch=release-13.1.1#patched compiled=2026-07-20T18:46:34+02:00
    logger=settings t=2026-08-10T18:37:26.198677108+02:00 level=error msg="Option '[alerting].enabled' cannot be true. Legacy Alerting is removed. It is no longer deployed, enhanced, or supported. Delete '[alerting].enabled' and use '[unified_alerting].enabled' to enable Graf>
    Error: ✗ invalid setting [alerting].enabled